### ISSUE TITLE
setup problem 

### ISSUE THREAD

**Issue by Nasr-Z1** [Crypto-AI/Stocktalk#4]
hello , i have problem setup Stocktalk , you see , 
i did
pip install stocktalk
then : python -m nltk.downloader vader_lexicon
but when i import stocktalk , i get this : 

>  import stocktalk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/stocktalk/__init__.py", line 2, in <module>
    from .visualize import visualize
  File "/usr/local/lib/python3.5/dist-packages/stocktalk/visualize.py", line 1, in <module>
    from bokeh.layouts  import row, column
ImportError: No module named 'bokeh'

please help , and thanks in advance

**Comment by anfederico** [comment]
Try "pip3 install bokeh"

**Comment by Nasr-Z1** [comment]
yeah it worked sorry was naive question , thanks any way :)
